version: "3.6"
services:
  swapnoneel-portfolio:
    build:
      context: $PWD/../..
      dockerfile: $PWD/pawan-portfolio/Dockerfile
    restart: always
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=pawan.com, www.pawan.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=pawan.com, www.pawan.com
      - LETSENCRYPT_EMAIL=pjha2186@gmail.com
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    depends_on:
      - pawan-react-portfolio
    links:
      - pawan-react-portfolio

networks:
  default:
    external:
      name: nginx-proxy